name: internal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/codexa:${{ github.sha }} --tag ghcr.io/${{ github.repository_owner }}/codexa:latest

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker Image to GitHub Container Registry
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository_owner }}/codexa:${{ github.sha }} && docker push ghcr.io/${{ github.repository_owner }}/codexa:latest
