name: internal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/codexa:$(date +%s)

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/codexa:$(date +%s)
