name: release

on:
  push:
    tags:
      - '*'

jobs:

  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag devoption/codexa:${{ github.ref_name }} --tag devoption/codexa:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker Image to Docker Hub
        run: docker push devoption/codexa:${{ github.ref_name }} && docker push devoption/codexa:latest
