name: release

on:
  push:
    tags:
      - '*'

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag devoption/codexa:${{ github.ref }} --tag devoption/codexa:latest

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker Image to Docker Hub
        run: docker push devoption/codexa:${{ github.ref }} && docker push devoption/codexa:latest
